version: "3.3"

##############################################################################
#                          ePAS HelpDesk Service                             #
# Configurazione per l'avvio di ePAS Helpdesk Service collegandosi ad un     #
# database di ePAS esistente                                                 #
##############################################################################

services:
  epas-helpdesk-service:
    image: ghcr.io/consiglionazionaledellericerche/epas-helpdesk-service:latest
    container_name: epas-helpdesk-service
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=prod

      # Impostazioni per l'autenticazione dell'applicazione
      # URI del servizio per il rilascio del token, es.: https://auth.iit.cnr.it/auth/realms/testing
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_JWT_ISSUER_URI}

      # OAUTH2_JWT_FIELD corrisponde al campo prelevato dal token JWT
      # OAUTH2_USER_AUTH_IDENTIFIER corrisponde al campo su ePAS di cui fare il match
      # con il campo del JWT_FIELD
      #- epas.security.oauth2.jwtfield=${OAUTH2_JWT_FIELD:-preferred_username}
      #- epas.security.oauth2.userAuthIdentifier=${OAUTH2_USER_AUTH_IDENTIFIER:-username}
      
      # Impostazione parametri per collegamento al db di ePAS
      - spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASS}

      # Attivazione ed impostazione parametri invio email
      - epas.helpdesk.email.enabled=${EMAIL_ENABLED:-false}
      #- spring.mail.host=${MAIL_HOST}
      #- spring.mail_port=${MAIL_PORT:-587}
      #- spring.mail.username=${MAIL_USERNAME}
      #- spring.mail.password=${MAIL_PASSWORD}
      #- spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:-true}
      #- spring.mail.properties.mail.smtp.starttls_enable=${MAIL_SMTP_STARTTLS_ENABLE:-true}
      #- epas.helpdesk.email.to=${EMAIL_TO:-epas@iit.cnr.it}
      #- epas.helpdesk.email.from=${EMAIL_FROM:-segnalazioni@epas.tools.iit.cnr.it}

      # Attivazione ed impostazione parametri integrazione OIL (CNR)
      - epas.helpdesk.oil.enabled=${OIL_ENABLED:-false}
      #- epas.helpdesk.oil.username=${OIL_USERNAME}
      #- epas.helpdesk.oil.password=${OIL_PASSWORD}
      #- epas.helpdesk.oil.url=${OIL_URL:-http://helpwildfly.si.cnr.it:8080}
      - epas.helpdesk.oil.categories=${OIL_CATEGORIES:-'50:Problemi Tecnici - ePAS,51:Problemi Amministrativi - ePAS'}

      # Da non cambiare a meno di cambiamenti di OIL
      #- epas.helpdesk.oil.instance=${OIL_INSTANCE:-HDSiper}

      # Da impostare solo per test, ignora la categoria selezionata dall'utente
      #- epas.helpdesk.oil.fixedCategory=${OIL_FIXED_CATEGORY:-67}

      #Da impostare per la gestione delle CORS
      #- epas.helpdesk.cors.allowedOrigins=https://[*].cnr.it
      #- epas.helpdesk.cors.allowedMethods=*
      #- epas.helpdesk.cors.maxAge=3600