version: "3.3"

##############################################################################
#                          ePAS HelpDesk Service                             #
# Configurazione per l'avvio di ePAS Helpdesk Service collegandosi ad un     #
# database di ePAS esistente                                                 #
##############################################################################

services:
  epas-service:
    image: docker-registry.services.iit.cnr.it/epas-helpdesk-service:latest
    container_name: epas-helpdesk-service
    ports:
      - 8080:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - spring_datasource_username=${DB_USER}
      - spring_datasource_password=${DB_PASS}
